/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5



/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <iostream>
#include <unistd.h>
using namespace std;

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	istream* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};


/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer



static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>


/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 99
#define YY_END_OF_BUFFER 100
static yyconst short int yy_accept[286] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  100,   98,   93,   92,   94,    8,   61,   62,
       75,   73,   48,   74,   47,   76,   89,   63,   72,   78,
       83,   80,   71,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   64,   65,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   44,   88,
       45,   77,    3,    2,    7,    5,   99,   99,   16,   15,
       16,   87,   99,   99,   87,    0,    4,    1,   91,   90,
       89,   95,   70,   79,   82,   81,   88,   88,   88,   88,
       88,   88,   88,   88,   22,   37,   23,   25,   88,   88,

       88,   88,   33,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   23,   88,   59,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,    6,   12,   13,    9,
       11,   10,   14,    0,    0,   86,   97,   90,   96,   95,
       88,   88,   88,   88,   19,   88,   88,   88,   88,   27,
       88,   32,   34,   88,   88,   88,   88,   88,   58,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   86,
       96,   88,   30,   88,   39,   31,   88,   88,   88,   28,
       29,   38,   36,   88,   88,   88,   88,   88,   88,   88,

       88,   88,   88,   88,   88,   88,   88,   88,   41,   88,
       88,   88,   35,   88,   60,   17,   18,   21,   88,   88,
       40,   88,   88,   20,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   42,   88,   88,   88,
       26,   88,   57,   88,   88,   88,   88,   88,   88,   88,
       88,   49,   88,   55,   54,   66,   56,   88,   88,   88,
       88,   85,   88,   88,   88,   88,   52,   88,   88,   68,
       24,   53,   88,   88,   51,   88,   69,   88,   67,   88,
       84,   43,   50,   46,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    3,    4,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    1,    1,    1,    1,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,   17,   18,
       19,   20,    1,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   31,   32,   31,   33,   34,   35,
       31,   36,   37,   38,   39,   40,   41,   31,   31,   31,
       42,   43,   44,    1,   45,    1,   46,   47,   48,   49,

       50,   51,   52,   53,   54,   31,   31,   55,   56,   57,
       58,   59,   31,   60,   61,   62,   63,   64,   65,   31,
       66,   31,   67,   68,   69,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[71] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    1,
        1,    1,    3,    1,    4,    5,    1,    1,    1,    1,
        1,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    1,    5,    1,    7,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    1,    6,    1,    1
    } ;

static yyconst short int yy_base[299] =
    {   0,
        0,    0,  494,  493,   67,   69,   68,   75,    0,    0,
      118,  188,  496,  499,  499,  499,  499,    0,  486,  499,
      499,  499,  499,  482,  478,  499,   67,  499,  499,   71,
      472,  472,  499,    0,   58,  112,   55,   63,  113,  115,
      119,   62,   57,  118,  113,  499,  499,   39,  440,  126,
      183,  178,  186,  121,  439,  164,  123,   40,  499,    0,
      499,  499,  499,  499,  499,  499,  499,  480,  499,  499,
      202,  499,  444,  443,  442,  480,  499,  499,  468,  467,
       82,    0,  499,  499,  499,  499,    0,  123,  174,  195,
      181,  194,  199,  183,    0,    0,  194,  208,  213,  218,

      213,  222,    0,  227,  237,  226,  237,  420,  431,  424,
      237,  419,  242,  421,    0,  426,   45,  428,  224,   59,
      428,  414,  418,  234,  411,  416,  499,  499,  499,  499,
      499,  499,  499,  426,  425,    0,  463,  451,    0,    0,
      244,  251,  242,  255,    0,  258,  246,  262,  259,    0,
      259,    0,    0,  264,  266,  274,  270,  403,    0,  414,
      271,  408,  407,  411,  410,  399,  394,  395,  401,  406,
      391,  398,  401,  389,  400,  387,  283,  386,  398,    0,
        0,  277,    0,  274,    0,    0,  287,  278,  285,    0,
        0,    0,    0,  290,  386,  383,  294,  394,  380,  382,

      380,  380,  393,  388,  383,  378,  375,  384,    0,  379,
      372,  383,    0,  367,    0,    0,    0,    0,  291,  297,
        0,  383,  378,    0,  371,  377,   49,  366,  370,  361,
      374,  373,  361,  358,  361,  358,    0,  347,  350,  288,
        0,  340,    0,  299,  298,  301,  297,  296,  292,  286,
      269,    0,  275,    0,    0,    0,    0,  274,  290,  266,
      223,    0,  220,  170,  174,  132,    0,  118,   91,    0,
        0,    0,   81,   57,    0,   54,    0,   53,    0,   40,
        0,    0,    0,    0,  499,  351,  358,  365,  372,  379,
      386,  391,  395,  398,  401,  405,  410,  413

    } ;

static yyconst short int yy_def[299] =
    {   0,
      285,    1,  286,  286,  287,  287,  288,  288,  289,  289,
      290,  290,  285,  285,  285,  285,  285,  291,  285,  285,
      285,  285,  285,  285,  285,  285,  292,  285,  285,  285,
      285,  285,  285,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  285,  285,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  285,  293,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  294,  285,  294,  291,  285,  285,  285,  295,
      292,  296,  285,  285,  285,  285,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,

      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  285,  285,  285,  285,
      285,  285,  285,  294,  285,  297,  291,  285,  298,  296,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  297,
      298,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,

      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,    0,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285

    } ;

static yyconst short int yy_nxt[570] =
    {   0,
       14,   15,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   34,   37,   38,   34,   34,   39,
       34,   40,   41,   42,   43,   34,   34,   44,   34,   34,
       45,   46,   14,   47,   34,   48,   35,   36,   49,   37,
       50,   34,   34,   51,   40,   34,   52,   53,   54,   55,
       56,   57,   34,   58,   45,   34,   59,   60,   61,   62,
       66,   67,   66,   70,   67,   68,   67,   68,   67,   80,
       70,   81,   83,   88,   94,  108,   91,   92,  103,   84,
      104,   93,   95,  125,   80,  109,   81,  126,  167,  246,

      284,  283,  168,  282,  172,  247,  281,   88,   94,   91,
       71,   92,  103,  173,  104,   93,   95,   71,   67,   67,
       72,   67,   72,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   89,   67,   67,   67,   67,   67,   96,
       99,  107,  280,   90,  101,   97,  105,  111,  100,   98,
      141,  105,  102,  106,  104,   95,  279,   89,  124,   67,
       74,   67,   67,   96,   99,  107,   90,  278,  101,   97,
      105,  111,  100,   98,  141,  105,  102,  106,  104,   95,
      117,  277,  124,  118,   67,   75,   67,   67,   67,   67,
       72,   67,   72,   67,   67,   67,   67,   67,   67,   67,

       67,   67,   67,  101,   67,   67,   67,   67,   67,   96,
      142,  102,  103,  120,  147,   97,  143,  144,  145,   98,
      146,  276,  148,  114,  275,  121,  122,  101,  123,   67,
       74,   67,   67,   96,  142,  102,  103,  147,  112,  113,
      143,  144,  145,   98,  146,  115,  148,  149,  128,  116,
      150,  151,  129,  152,   67,   75,   67,   67,  130,  153,
      154,  131,  155,  132,  156,  133,  157,  274,  161,  170,
      148,  149,  177,  182,  150,  151,  183,  152,  184,  273,
      185,  186,  187,  153,  154,  171,  155,  188,  156,  163,
      157,  161,  189,  190,  148,  191,  177,  182,  192,  193,

      183,  194,  184,  164,  185,  186,  187,  197,  213,  216,
      217,  188,  218,  219,  220,  221,  189,  190,  191,  224,
      240,  241,  192,  193,  194,  259,  271,  272,  270,  269,
      268,  197,  213,  216,  217,  267,  218,  219,  220,  221,
      266,  265,  264,  224,  240,  241,  263,  262,  261,  259,
      271,   63,   63,   63,   63,   63,   63,   63,   65,   65,
       65,   65,   65,   65,   65,   69,   69,   69,   69,   69,
       69,   69,   67,   67,   67,   67,   67,   67,   67,   73,
       73,   73,   73,   73,   73,   73,   76,  260,   76,   76,
       76,   76,   76,   82,   82,  258,   82,   82,   87,  257,

       87,   87,  134,  134,  139,  256,  139,  139,  140,  255,
      140,  140,  180,  180,  254,  180,  181,  253,  181,  181,
      252,  251,  250,  249,  248,  245,  244,  243,  242,  239,
      238,  237,  236,  235,  234,  233,  232,  231,  230,  229,
      228,  227,  226,  225,  223,  222,  215,  214,  212,  211,
      210,  209,  208,  207,  206,  205,  204,  203,  202,  201,
      200,  199,  198,  196,  195,  138,  137,  136,  135,  179,
      178,  176,  175,  174,  169,  166,  165,  162,  160,  159,
      158,  138,   79,  137,  135,  136,  135,  127,  119,  110,
       86,   85,   79,   78,   77,  285,   64,   64,   13,  285,

      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285
    } ;

static yyconst short int yy_chk[570] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        5,    7,    6,    7,    5,    5,    6,    6,    8,   27,
        8,   27,   30,   35,   38,   48,   37,   37,   42,   30,
       43,   37,   38,   58,   81,   48,   81,   58,  117,  227,

      280,  278,  117,  276,  120,  227,  274,   35,   38,   37,
        7,   37,   42,  120,   43,   37,   38,    8,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   36,   11,   11,   11,   11,   11,   39,
       40,   45,  273,   36,   41,   39,   44,   50,   40,   39,
       88,   57,   41,   44,   54,   50,  269,   36,   57,   11,
       11,   11,   11,   39,   40,   45,   36,  268,   41,   39,
       44,   50,   40,   39,   88,   57,   41,   44,   54,   50,
       54,  266,   57,   54,   11,   11,   11,   11,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,

       12,   12,   12,   52,   12,   12,   12,   12,   12,   51,
       89,   52,   53,   56,   94,   51,   90,   91,   92,   51,
       93,  265,   97,   52,  264,   56,   56,   52,   56,   12,
       12,   12,   12,   51,   89,   52,   53,   94,   51,   51,
       90,   91,   92,   51,   93,   53,   97,   98,   71,   53,
       99,  100,   71,  101,   12,   12,   12,   12,   71,  102,
      104,   71,  105,   71,  106,   71,  107,  263,  111,  119,
      113,   98,  124,  141,   99,  100,  142,  101,  143,  261,
      144,  146,  147,  102,  104,  119,  105,  148,  106,  113,
      107,  111,  149,  151,  113,  154,  124,  141,  155,  156,

      142,  157,  143,  113,  144,  146,  147,  161,  177,  182,
      184,  148,  187,  188,  189,  194,  149,  151,  154,  197,
      219,  220,  155,  156,  157,  240,  259,  260,  258,  253,
      251,  161,  177,  182,  184,  250,  187,  188,  189,  194,
      249,  248,  247,  197,  219,  220,  246,  245,  244,  240,
      259,  286,  286,  286,  286,  286,  286,  286,  287,  287,
      287,  287,  287,  287,  287,  288,  288,  288,  288,  288,
      288,  288,  289,  289,  289,  289,  289,  289,  289,  290,
      290,  290,  290,  290,  290,  290,  291,  242,  291,  291,
      291,  291,  291,  292,  292,  239,  292,  292,  293,  238,

      293,  293,  294,  294,  295,  236,  295,  295,  296,  235,
      296,  296,  297,  297,  234,  297,  298,  233,  298,  298,
      232,  231,  230,  229,  228,  226,  225,  223,  222,  214,
      212,  211,  210,  208,  207,  206,  205,  204,  203,  202,
      201,  200,  199,  198,  196,  195,  179,  178,  176,  175,
      174,  173,  172,  171,  170,  169,  168,  167,  166,  165,
      164,  163,  162,  160,  158,  138,  137,  135,  134,  126,
      125,  123,  122,  121,  118,  116,  114,  112,  110,  109,
      108,   80,   79,   76,   75,   74,   73,   68,   55,   49,
       32,   31,   25,   24,   19,   13,    4,    3,  285,  285,

      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
#define INITIAL 0
#line 2 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
#include "yacc.hpp"
#include <stdlib.h>
#include <list>
#include <fstream>
#include "Symbol_Table.h"

int mylineno,mywords,mydigit,myfloat,space = 0;
char* temp;
int line=1;
int col=0;
string v="";
void yyerror(char *);
char * copystr(const char* s);
#define com1 1

#define com2 2
#define com3 3
#define strError 4

#define incl 5

#line 28 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
#define MAX_INCLUDE_DEPTH 10
YY_BUFFER_STATE include_stack[MAX_INCLUDE_DEPTH];
int include_stack_ptr = 0;
#line 573 "lex.yy.cc"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif


#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yyFlexLexer::yylex()
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 32 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"


#line 703 "lex.yy.cc"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = &cin;

		if ( ! yyout )
			yyout = &cout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 286 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 499 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 34 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{BEGIN(com1); col+=2;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 35 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{line++;BEGIN(INITIAL);col=0;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 36 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 39 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{BEGIN(com2);col+=2;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 40 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{line++;col=0;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 41 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{ BEGIN(INITIAL);col+=2;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 42 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 45 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{v="";BEGIN(com3); col+=1; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 47 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{*yytext++ ='\n'; v+="\n"; line++; col=0;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 48 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{*yytext++ ='\t'; v+="\t"; col+=8;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 49 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{*yytext++ ='\r'; v+="\r"; col+=8;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 50 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{*yytext++ ='\b'; v+="\b"; col+=8;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 51 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{*yytext++ ='\f'; v+="\f"; col+=8;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 52 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{*yytext++ ='\v'; v+="\v"; col+=8;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 54 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{BEGIN(INITIAL);col+=1; const char * g=new char;
g=v.data();yylval.sval=(char *) g; return STRINGS;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 57 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;v.append(yytext);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 59 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return (BEG);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 60 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return (CLASS);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 61 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return END;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 62 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return FALSE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 63 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return err_FALSE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 64 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return FI;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 65 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return IN;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 66 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return INHERITS;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 67 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return IS;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 68 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return ISVOID;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 69 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return LET;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 70 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return LOOP;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 71 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return POOL;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 72 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return CASE;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 73 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return ESAC;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 74 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;yylval.modi=New; yylval.my_modifier=new my_modifiers(New); return NEW; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 75 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return OF;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 76 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return NOT;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 77 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return TRUE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 78 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return err_TRUE;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 79 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return IF;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 80 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return THEN;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 81 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return ELSE;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 82 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return WHILE;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 83 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{mywords++; col+=yyleng; yylval.sval=copystr(yytext); return ID;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 84 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return SUPER;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 85 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return NAMESPACE;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 86 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return(LC);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 87 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return(RC);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 88 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return IMPLEMENTS;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 89 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return(DOT);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 90 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return COMMA;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 91 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng; yylval.modi=Public;yylval.my_modifier=new  my_modifiers(Public);  return PUBLIC;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 92 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;yylval.modi=Protected;yylval.my_modifier=new  my_modifiers(Protected);return PROTECTED;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 93 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;yylval.modi=Internal;yylval.my_modifier=new  my_modifiers(Internal);return INTERNAL;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 94 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;yylval.modi=Private;yylval.my_modifier=new  my_modifiers(Private);return PRIVATE;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 95 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;yylval.modi=Abstract; yylval.my_modifier=new my_modifiers(Abstract);return (ABSTRACT);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 96 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;yylval.modi=Sealed; yylval.my_modifier=new  my_modifiers(Sealed);return SEALED;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 97 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return RETURN;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 98 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return SWITCH;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 99 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return DELETE;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 100 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return ND;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 101 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return AOR;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 102 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return VOID;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 103 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return LP;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 104 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return RP;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 105 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return COLON;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 106 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return LB;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 107 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return RB;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 108 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;yylval.modi=Static;yylval.my_modifier=new  my_modifiers(Static);return STATIC;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 109 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;yylval.modi=Readonly; yylval.my_modifier=new  my_modifiers(Readonly);return READONLY;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 110 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;yylval.modi=Virtual; yylval.my_modifier=new  my_modifiers(Virtual);return VIRTUAL;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 111 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;yylval.modi=Override;yylval.my_modifier=new  my_modifiers(Override);return OVERRIDE;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 112 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return ASSIGN;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 113 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return AT;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 114 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return SEMICOLON;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 115 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return PLUS;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 116 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return MINUS;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 117 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return STAR;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 118 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return DIV;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 119 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return NEGATE;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 120 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return LT;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 121 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return LE;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 122 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return GT;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 123 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return GE;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 124 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return RE;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 125 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return EQUAL;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 126 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;return INTERFACE;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 128 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{BEGIN(incl);}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 130 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{
	if(include_stack_ptr>=MAX_INCLUDE_DEPTH)
	{
		yyerror("Includes nested too deeply");
		exit(1);
	}
	include_stack[include_stack_ptr++]=YY_CURRENT_BUFFER;
	yyin=new ifstream(yytext);
	if(!*yyin)
		yyerror("Included file not found");
	yy_switch_to_buffer(yy_create_buffer(yyin,YY_BUF_SIZE));
	BEGIN(INITIAL);}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 142 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"

	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(com1):
case YY_STATE_EOF(com2):
case YY_STATE_EOF(com3):
case YY_STATE_EOF(strError):
case YY_STATE_EOF(incl):
#line 143 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{
	if (--include_stack_ptr<0)
		yyterminate();
	else
	{
		yy_delete_buffer(YY_CURRENT_BUFFER);
		yy_switch_to_buffer(include_stack[include_stack_ptr]);
	}
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 152 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;mywords++; yylval.sval=copystr(yytext); return ID;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 153 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;mydigit++; yylval.ival=atoi(yytext); return INT;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 154 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;myfloat++;yylval.fval=(float)atof(yytext); return FLOAT;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 155 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=yyleng;myfloat++;  yylval.fval=(float)atof(yytext); return FLOAT;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 156 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col=0;mylineno++;space++; line++;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 157 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col+=8;space++;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 158 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{col++;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 160 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{yyerror("LEXICAL ERROR: INVALID IDENTIFIER NAME"); col+=yyleng;mywords++; return ID;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 161 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{yyerror("LEXICAL ERROR: INVALID IDENTIFIER NAME"); col+=yyleng;mywords++;  return ID;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 162 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{yyerror("LEXICAL ERROR: STRING ERROR Forget to close srting"); col+=yyleng;mywords++; return STRINGS;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 163 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
{yyerror("LEXICAL ERROR: UNKNOWN CHARACTER");return ERROR;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 164 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"
ECHO;
	YY_BREAK
#line 1310 "lex.yy.cc"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */

yyFlexLexer::yyFlexLexer( istream* arg_yyin, ostream* arg_yyout )
	{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 1;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = 0;

	yy_current_buffer = 0;

#ifdef YY_USES_REJECT
	yy_state_buf = new yy_state_type[YY_BUF_SIZE + 2];
#else
	yy_state_buf = 0;
#endif
	}

yyFlexLexer::~yyFlexLexer()
	{
	delete yy_state_buf;
	yy_delete_buffer( yy_current_buffer );
	}

void yyFlexLexer::switch_streams( istream* new_in, ostream* new_out )
	{
	if ( new_in )
		{
		yy_delete_buffer( yy_current_buffer );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE ) );
		}

	if ( new_out )
		yyout = new_out;
	}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
	{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
	}

void yyFlexLexer::LexerOutput( const char* buf, int size )
	{
	(void) yyout->write( buf, size );
	}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

int yyFlexLexer::yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

yy_state_type yyFlexLexer::yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 286 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 286 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 285);

	return yy_is_jam ? 0 : yy_current_state;
	}


void yyFlexLexer::yyunput( int c, register char* yy_bp )
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}


int yyFlexLexer::yyinput()
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


void yyFlexLexer::yyrestart( istream* input_file )
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


void yyFlexLexer::yy_load_buffer_state()
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( istream* file, int size )
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


extern "C" int isatty YY_PROTO(( int ));
void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, istream* file )

	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

	b->yy_is_interactive = 0;
	}


void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#endif


#ifndef YY_NO_SCAN_STRING
#endif


#ifndef YY_NO_SCAN_BYTES
#endif


#ifndef YY_NO_PUSH_STATE
void yyFlexLexer::yy_push_state( int new_state )
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
void yyFlexLexer::yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
int yyFlexLexer::yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif


void yyFlexLexer::LexerError( yyconst char msg[] )
	{
	cerr << msg << '\n';
	exit( YY_EXIT_FAILURE );
	}


/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 164 "c:\\Users\\SONY\\Desktop\\compiler - with code generate - Copy - Copy\\LexTest\\lex.l"

